### ISSUE TITLE
Filter - Filter dan label belum sesuai

### ISSUE THREAD

**Issue by ekojs** [phpid-jakarta/ajari-koding#12]
**Penjelasan bug/erroe**
Ketika memilih filter **Machine Learning** yang berisi 2 konten, namun di konten tersebut tidak ada label machine learning.

**Cuplikan gambar**
[Imgur](https://i.imgur.com/vZgwmpb.png)

**Comment by mazipan** [comment]
Debug result: the item contain `machine learning` tag, but somehow showing wrong tag. my first guess is because it derived state from it's props.

Root cause: the looping item have no key
Solution: 
- Generate `id` field based on title
- Using `keyed` each on looping
- Add active/deactivated state on tag click

Commit: https://github.com/phpid-jakarta/ajari-koding/commit/21d918b85f4202523e629d3752ce6bce4b4b9dca
